### ISSUE TITLE
Add MPR installation instructions

### ISSUE THREAD

**Issue by hwittenborn** [taiki-e/parse-changelog#22]
I've added parse-changelog to the [MPR](https://mpr.makedeb.org/packages/parse-changelog), a user-led platform for people to submit and publish packages for Debian and Ubuntu based systems. It's a platform I've personally made, but it's already seen a fair bit of adoption. With that, I was wondering if you'd like to add instructions for installing parse-changelog from the MPR.

If you do decide to go the route of adding the instructions, you may also want to add setup instructions for the [Prebuilt-MPR](https://docs.makedeb.org/prebuilt-mpr/getting-started/), which provides a repository containing prebuilt packages from the MPR (as the MPR itself only contains files to build packages), thought that's up to you.

Regardless of what you choose to do, I also just wanted to say thanks for making this, I just stumbled on this a bit ago and I'm immediately going to start using it in my projects :).

**Comment by taiki-e** [comment]
Thanks! I would accept a PR to add MPR installation instructions. A format similar to [cargo-llvm-cov's AUR installation instructions](https://github.com/taiki-e/cargo-llvm-cov#via-aur-archlinux) would be good.

**Comment by hwittenborn** [comment]
Great! I'll try to get something going soon :)
