### ISSUE TITLE
Remove links from title

### ISSUE THREAD

**Issue by IgnisDa** [taiki-e/parse-changelog#32]
For example, https://github.com/github-changelog-generator/github-changelog-generator generates headings in the following format:

```markdown
## [v1.0.0-beta.55](https://github.com/ignisda/ryot/tree/v1.0.0-beta.55) (2023-06-05)

[Full Changelog](https://github.com/ignisda/ryot/compare/v1.0.0-beta.54...v1.0.0-beta.55)

**Closed issues:**

- Error: Failed to read source file. [\#116](https://github.com/IgnisDa/ryot/issues/116)
```
The above header is still in accordance with keepachangelog's spec but `parse-changelog` does not really parse it correctly.

**Comment by IgnisDa** [comment]
Closing this issue as it is a feature request for cargo-dist.

**Comment by IgnisDa** [comment]
Maybe this library can also parse the title itself to get just the name of the release (and get rid of the links etc).

**Comment by taiki-e** [comment]
I think this format itself is already supported.

```console
# body
$ parse-changelog CHANGELOG.md 
[Full Changelog](https://github.com/ignisda/ryot/compare/v1.0.0-beta.54...v1.0.0-beta.55)

**Closed issues:**

- Error: Failed to read source file. [\#116](https://github.com/IgnisDa/ryot/issues/116)

$ parse-changelog CHANGELOG.md --title
[v1.0.0-beta.55](https://github.com/ignisda/ryot/tree/v1.0.0-beta.55) (2023-06-05)

$ parse-changelog CHANGELOG.md --json   
{"1.0.0-beta.55":{"version":"1.0.0-beta.55","title":"[v1.0.0-beta.55](https://github.com/ignisda/ryot/tree/v1.0.0-beta.55) (2023-06-05)","notes":"[Full Changelog](https://github.com/ignisda/ryot/compare/v1.0.0-beta.54...v1.0.0-beta.55)\n\n**Closed issues:**\n\n- Error: Failed to read source file. [\\#116](https://github.com/IgnisDa/ryot/issues/116)"}}
```


What is your actual request? Is it to remove the link from the title? If so, this is not a major request like "alternate header format" but a minor request regarding the format in which the parse-changelog retains the text.

**Comment by taiki-e** [comment]
Currently, the title is stored as str, but if we delete links, we need to store it as String or Cow because we need to concat texts that removed links.

https://github.com/taiki-e/parse-changelog/blob/43a2fd1836e5d8a8546d9eadcea224c40c8f11f3/src/lib.rs#L288

**Comment by IgnisDa** [comment]
Could we store both the link as well as the title?

**Comment by taiki-e** [comment]
> Could we store both the link as well as the title?

Do you mean to have both titles that contain links and titles that have links removed?

**Comment by taiki-e** [comment]
I created a patch [here](https://github.com/taiki-e/parse-changelog/tree/title-no-link).

```console
$ parse-changelog CHANGELOG.md --title-no-link
v1.0.0-beta.55 (2023-06-05)
```

@IgnisDa  Is it the output you expect?

**Comment by IgnisDa** [comment]
Yep would be exactly what I need.
